### PR TITLE
Fixes #104: correctly parse id repr for Rust 1.78+

### LINKED ISSUE #104: Investigate Nightly CI failure
As seen on main: https://github.com/bnjbvr/cargo-machete/actions/runs/7856593096/job/21439530326

### LINKED ISSUE #114: [Rust 1.77.0] cargo machete --with-metadata panicking
The new stable version was just released & the crate is panicking when run with `--with-metadata`.
```
Analyzing dependencies of crates in this directory...
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
thread '<unnamed>' panicked at src/search_unused.rs:362:14:
the current package must be in the dependency graph
```
This happens about 19 times in the polars workspace: https://github.com/pola-rs/polars

### PR DESCRIPTION
**Pull request by bnjbvr**
This updates to the new pkgid spec used after Rust 1.77.

Fixes #104.
Fixes #114.

### CODE REVIEW

**Comment by utkarshgupta137** [comment]
Since this is probably breaking the CI for everyone who has stable testing, may I suggest merging this soon?

**Comment by bnjbvr** [comment]
Thanks, I'd really like a test by someone on windows though, since paths may be different there (notably slash vs backslash).

File: src/search_unused.rs [hunk 1]
```diff
@@ -352,12 +352,51 @@ pub(crate) fn find_unused(
...
+                            let mut hash_split = subset.split('#');
+                            // Skip everything before the hash.
+                            hash_split.next();
+                            // Now in the rest, take everything up to the @.
+                            temp = hash_split.next().and_then(|end| end.split('@').next());
+                        } else {
+                            // Otherwise, take everything up to the #.
+                            temp = subset.split('#').next();
+                        }
+                    }
```
Comment (epage) [inline src/search_unused.rs:394]: Or you could use [cargo_util_schemas::core::PackageIdSpec::parse](https://docs.rs/cargo-util-schemas/latest/cargo_util_schemas/core/struct.PackageIdSpec.html#method.parse) and then extract the path from the URL.  Then if we extend the `PackageIdSpec` syntax, its just a dependency update away.

btw the spec for Specs is at https://doc.rust-lang.org/cargo/reference/pkgid-spec.html

**Comment by epage** [comment]
You shouldn't need any platform-specific testing done.  If the output of the old (opaque) id worked for you then extracting it should work here as well because they are both URLs and are platform-independent and you already had to be handling any platform-specific logic for the old id format.

**Comment by bnjbvr** [comment]
@epage Ah thanks for the information, I hadn't realized this was platform-independent.
